# -*- encoding: utf-8 -*-
#
=begin
#Alfresco Content Services REST API

#**Search API** Provides access to the search features of Alfresco Content Services.

OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

$:.push File.expand_path("../lib", __FILE__)
require "alfresco/version"

Gem::Specification.new do |s|
  s.name        = "alfresco"
  s.version     = Alfresco::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Élisson Michael", "Swagger-Codegen"]
  s.email       = ["elissonmichael@yahoo.com.br"]
  s.homepage    = "https://github.com/rhuanbarreto/alfresco-ruby-client"
  s.summary     = "Alfresco Content Services REST API Ruby Gem"
  s.description = "**Search API** Provides access to the search features of Alfresco Content Services. "
  s.license     = "Nonstandard"
  s.required_ruby_version = ">= 1.9"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'
  s.add_development_dependency 'vcr', '>= 3.0.1', '~> 5.1'
  s.add_development_dependency 'webmock', '>= 1.24.3', '~> 2.3'
  s.add_development_dependency 'autotest', '>= 4.4.6', '~> 5.0'
  s.add_development_dependency 'autotest-rails-pure', '~> 4.1', '>= 4.1.2'
  s.add_development_dependency 'autotest-growl', '~> 0.2', '>= 0.2.16'
  s.add_development_dependency 'autotest-fsevent', '~> 0.2', '>= 0.2.12'

  s.files         = `find *`.split("\n").uniq.sort.select{|f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
