=begin
#Alfresco Content Services REST API

#**Search API** Provides access to the search features of Alfresco Content Services. 

OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Alfresco::RequestDefaults
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RequestDefaults' do
  before do
    # run before each test
    @instance = Alfresco::RequestDefaults.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RequestDefaults' do
    it 'should create an instance of RequestDefaults' do
      expect(@instance).to be_instance_of(Alfresco::RequestDefaults)
    end
  end
  describe 'test attribute "text_attributes"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "default_fts_operator"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["AND", "OR"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.default_fts_operator = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "default_fts_field_operator"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["AND", "OR"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.default_fts_field_operator = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "namespace"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "default_field_name"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

