=begin
#Alfresco Content Services REST API

#**Search API** Provides access to the search features of Alfresco Content Services. 

OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Alfresco::RequestSortDefinition
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RequestSortDefinition' do
  before do
    # run before each test
    @instance = Alfresco::RequestSortDefinition.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RequestSortDefinition' do
    it 'should create an instance of RequestSortDefinition' do
      expect(@instance).to be_instance_of(Alfresco::RequestSortDefinition)
    end
  end
end

