=begin
#Alfresco Content Services REST API

#**Search API** Provides access to the search features of Alfresco Content Services. 

OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Alfresco::RequestScope
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RequestScope' do
  before do
    # run before each test
    @instance = Alfresco::RequestScope.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RequestScope' do
    it 'should create an instance of RequestScope' do
      expect(@instance).to be_instance_of(Alfresco::RequestScope)
    end
  end
  describe 'test attribute "locations"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["nodes", "versions", "deleted-nodes"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.locations = value }.not_to raise_error
       #end
    end
  end

end

